### ISSUE TITLE
D3 Chart Components

### ISSUE THREAD

**Issue by greenafrican** [woocommerce/wc-admin#164]
## Designs
- [InVision](https://automattic.invisionapp.com/d/main#/console/14672444/305102856/preview)
- [Graph Component P2](https://teamxthings.wordpress.com/2018/06/27/graph-component/)

**Master Thread:** https://teamxthings.wordpress.com/2018/06/05/master-thread-analytics-reports/

## Latest Screengrab
![legend](https://user-images.githubusercontent.com/1160732/43209085-1b57a712-902c-11e8-94dd-113391f463b0.gif)

## Components
This is the parent issue for all components related to the charts.

- [x] D3 Base Component #73 
- [x] Chart Utilities + Tests #120 
- [x] Bars + Lines #120 
- [x] Axis #120 
- [x] Tooltip #120 
- [x] README + JSDocs #184
- [x] Legend #189
- [x] Legend Transitions, Mouseovers + Selection #189
- [x] Chart Card Components (title, layout, design, etc.) 
- [x] **DESIGN REVIEW**
- [x] Follow up on design review feedback #350 
- [x] Legend Behavior: Standard Chart Vs. Comparison Chart #378
- [x] Standard Chart: Legend Order #379
- [x] Define specific color stops for charts with five series or less #375
- [x] Charts: Update styles per different time periods #382 
- [x] Chart Legend: Update checkbox styles to outline when unchecked #377
- [x] Update the tool tip for standard graphs per #373 
- [x]  Bug - Date range picker and x-axis ticks out of snyc per #374
- [x]  Bug - Chart: X-Axis overflowing container #376
- [x] Bug Negative numbers causing console errors #391
- [x] Prevent user from disabling all series in a chart legend #383
- [x] Chart Header improvements #361 
- [x] Hookup data layers 
- [ ] Update README
- [x] a11y for keyboard only & screen readers as per #208 
- [x] Bar <> Line Transitions
- [ ] Refactor

**Comment by timmyc** [comment]
I'm closing this one out Rob since most all the child tasks have been completed. The refactor/README updates I think we can open up new issues for if you feel the need.
