### ISSUE TITLE
Analytics: Downloads Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#173]
Blocked by #97 

All base analytics components are being developed for the Revenue Report. Once those components ship, work can commence on this report.

**Design Post**: p6riRB-3dU-p2
**Mock API**: [https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_downloads_stats](get_reports_downloads_stats)
**REST API Post**: p7bje6-15q-p2

![image](https://user-images.githubusercontent.com/22080/42393582-a89d99c2-810b-11e8-9fe7-e06fa56bb9dd.png)

## Child Tasks
- [x] #428 REST API: Downloads reports endpoint
- [x] #922 Analytics: Create Downloads Report Page
- [x] #914 Analytics: Downloads Report Chart
- [ ] #915 Analytics: Downloads Report Table
- [x] #263 Analytics: Downloads Report Advanced Filters

**Comment by timmyc** [comment]
💯 AWESOME!
