### ISSUE TITLE
Analytics: Stock Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#174]
All base analytics components are being developed for the Revenue Report. Once those components ship, work can commence on this report.

**Design Post**: p6riRB-3dV-p2
**Mock API**: NA uses existing endpoints modified for `v3`
**REST API Post**: p7bje6-16i-p2

![image](https://user-images.githubusercontent.com/22080/42393694-13abdd6e-810c-11e8-9272-d0d9ccfb471e.png)

### Child Tasks

- [x] #919 REST API: Products Endpoint Low Stock Query
- [x] #921 Analytics: Create Stock Report Page
- [ ] #920 Analytics: Stock Report Table
