### ISSUE TITLE
Analytics: Customers Reports

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#175]
All base analytics components are being developed for the Revenue Report. Once those components ship, work can commence on this report.

**Design Post**: p6riRB-3dW-p2
**Mock API**: [https://href.li/?https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_customers](get_reports_customers)
**REST API Post**: p7bje6-16h-p2

![313189259](https://user-images.githubusercontent.com/22080/49551103-c3502500-f8a2-11e8-8f7e-42e6f3a0cdbb.png)

### Child Tasks
- [x] #916 REST API: Implement /reports/customers endpoint
- [x] #918 Analytics: Customers Report Table
- [x] #1027 Advanced Filter Date
- [x] #1028 Advanced Filter Numerical
- [x] #1029 Name Advanced Filter
- [x] #1030 Username Advanced Filter
- [x] #1031 Email Advanced Filter
- [x] #1032 Country Advanced Filter
- [x] #1033 Signup Advanced Filter
- [x] #1033 Last Active Advanced Filter
- [x] #1034 Number of Orders Advanced Filter - Blocked by #1028 
- [x] #1034 Total Spend Advanced Filter - Blocked by #1028
- [x] #1034 Average Order Value Advanced Filter - Blocked by #1028 
- [x] #1084 Add search box to tables

**Comment by kwok0781** [comment]
While this filter is a great idea, it would be great to get these in a graphical form to analyze repeat customers, lifetime value of customers, avg duration until repeat purchase, etc.  

Suggest laying out this data in a scatter plot with the y-axis as Lifetime Value and x-axis as number of orders.  Every dot can be clicked to deep dive into a user's profile so that we can better understand why they are such good customers:

![image](https://user-images.githubusercontent.com/4407754/61540700-b4546680-aa70-11e9-9c0b-3422f764e93d.png)

Currently, it is very difficult to analyze who our top customers are in WC.  We need to constantly export all the data out to run analysis
