### ISSUE TITLE
Component: Advanced Filter

### ISSUE THREAD

**Issue by psealock** [woocommerce/wc-admin#256]
**Designs**:  p6riRB-3mb-p2

![screen shot 2018-08-01 at 12 12 59 pm](https://user-images.githubusercontent.com/1922453/43493899-5253bb72-9584-11e8-9e6e-62e6d7756000.png)

## Child Issues
- [x] Search Box https://github.com/woocommerce/wc-admin/issues/257
- [x] Select https://github.com/woocommerce/wc-admin/issues/258
- [x] Add a filter button https://github.com/woocommerce/wc-admin/issues/259 Fixed in https://github.com/woocommerce/wc-admin/pull/276
- [x] Create a reusable Card to contain UI elements https://github.com/woocommerce/wc-admin/issues/260 Fixed in https://github.com/woocommerce/wc-admin/pull/276
- [x] Write logic to update and persist parameters via URL query https://github.com/woocommerce/wc-admin/issues/261
- [x] Fetch custom order statuses, [api](https://github.com/woocommerce/woocommerce/blob/master/includes/api/v1/class-wc-rest-orders-controller.php#L902-L910)
- [x] UI translation audit https://github.com/woocommerce/wc-admin/issues/285 https://github.com/woocommerce/wc-admin/pull/457
- [x] Search component to render tokens in the field instead of below
- [x] Remove is/is_not in favour of includes/excludes https://github.com/woocommerce/wc-admin/pull/457
