### ISSUE TITLE
Design: Tabular Data Master Thread

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#436]
This issue serves as an index for all design and experience issues relating to the tabular data component. 

**Table Header:**

- [x] Add filter / search per #394
- [x] Update download button to match design documentation per #442
- [x] Update color of ellipsis menu toggles to WooCommerce purple per #443

**Table:**

- [x] Update column alignment per #444
- [x] Reposition sorting chevron to the right of first column label per #446
- [x] Update padding / margin on checkbox column per #447
- [x] Update style of column that is actively being sorted per #448
- [x] Update ViewMore per #415
- [x] Make tabular data independent of chart Interval per #385
- [x] Update focus style for table cells with links per #449
- [x] Add gradient overlay when table overflows the viewport per #450

**Table Footer:**

- [x] Pagination alignment per #451

**Comment by timmyc** [comment]
All checked off - can we close this issue now @LevinMedia ?
