### ISSUE TITLE
Product Detail Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#564]
Since this is some distinct functionality that is an extension of the standard chart in the products report, it seemed wise to break it out into its own issue [see David's comment for context](https://github.com/woocommerce/wc-admin/issues/534#issuecomment-430759198).

<img width="1361" alt="screen shot 2018-10-24 at 12 16 40 pm" src="https://user-images.githubusercontent.com/4500952/47455580-0dfc5e80-d787-11e8-9016-bed4373fd243.png">

Full detail at the second in the second half of the Product Report post here: p6riRB-3dP-p2

When the product report is filtered to look at a single product, (either by using the filter at the top of the report, or clicking a product title in the tabular data) the variation filter should appear when applicable and the chart should respond accordingly.

Related - for the product detail screen, we'll also need to build out / include the comparison chart detailed at: p6riRB-3u4-p2

<img width="748" alt="screen shot 2018-10-17 at 12 31 59 pm" src="https://user-images.githubusercontent.com/4500952/47111552-b307bc00-d208-11e8-8bcb-e84cdd1e9f5c.png">

@LevinMedia what is the anticipated changes to the tabular data when in the detail view? Raw sales data for the product/variation(s) selected over the time period? 

### Child Tasks
- [x] Add Variations filter https://github.com/woocommerce/wc-admin/issues/681
- [x] Add Variations autocompleter https://github.com/woocommerce/wc-admin/pull/742
- [x] Variations Table https://github.com/woocommerce/wc-admin/issues/762
- [x] Segmentation of API response. Trackable in p7bje6-1bY-p2
- [x] VariationImage for autocompleter #832
- [x] Comparison Chart: design #816
- [x] Comparison Chart: API #695
