### ISSUE TITLE
Component: Date Picker

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#59]
The DatePicker is one of the more complex components that has been displayed in the designs thus far. The best way to get familiar with the concept is to ready the original thread by @LevinMedia and watch the screen cast he provides in p6riRB-38x-p2

This component will be present on all new Analytics pages as setting date range on all reports is a primary function for all reports. Additionally the Date Picker will be utilized in the Store Performance block.

This issue will act as a parent issue for all related tasks to the Date Picker. Since there are a number of components that comprise the feature - I feel it is best to break it up into child tasks to allow multiple people to work on it simultaneously - and prevent the dreaded long-running _large_ pull requests from happening 😄 

__Child Issues__
- [x] #58 Component: Segmented Control
- [x] #60 Discovery: Custom Calendar Range Pickers
- [x] #61 Component: Preset Group
- [x] #62 Component: Date Picker Display / Launcher

__Lo Fi Designs__

<img width="747" alt="datepicker-1" src="https://user-images.githubusercontent.com/22080/40150452-8b4d8b02-592e-11e8-9064-b27b2e8e0b0a.png">

<img width="745" alt="datepicker-2" src="https://user-images.githubusercontent.com/22080/40150457-90a8623e-592e-11e8-8e43-2106c8bba539.png">

<img width="556" alt="date-picker3" src="https://user-images.githubusercontent.com/22080/40150467-9693e1a0-592e-11e8-9827-83aa0db8fa38.png">
