### ISSUE TITLE
Chart: x-axis refactor master thread

### ISSUE THREAD

**Issue by greenafrican** [woocommerce/wc-admin#632]
Master P2 Thread: p6riRB-3C9

## Sub-tasks
- [x] Don’t include the last date of the selected period if it produces uneven primary x-axis ticks - #635 
- [x] Display the full year - #638
- [x] Only include the year on first secondary x-axis tick of that year - #639
- [x] When the x-axis includes more than 62 days, switch the primary x-axis ticks to months, and only show the year on the secondary axis  #685 + #785
