### ISSUE TITLE
Analytics: Table Header Component

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#94]
**Designs**: [inVision](https://automattic.invisionapp.com/share/4NN1HQC5B8F#/308750696_Overview)
**Master Thread**: p6riRB-3lZ-p2

The table component should have a header, which can have an EllipsisMenu and "download" button in the simple case:

![screen shot 2018-07-18 at 4 50 41 pm](https://user-images.githubusercontent.com/541093/42907044-ba039bf0-8aaa-11e8-995f-e17bea8c21ab.png)

Tables can also allow for filtering & comparing, with a multi-select filter component & compare button (active when multiple rows are selected)

![screen shot 2018-07-18 at 4 50 36 pm](https://user-images.githubusercontent.com/541093/42907045-ba156ba0-8aaa-11e8-87c7-bddbaf6881c9.png)

(issue updated to a "master" issue, to reflect new designs, by @ryelle)

- [x] Make column toggles in EllipsisMenu functional | PR #268 
- [x] Update header/toggle functionality to handle "required" columns | Issue #271, PR #275
- [x] Add compare button with checkboxes per-row | Issue #94, PR TBD
- [x] Add filter search | Issue #94, PR TBD

**Comment by ryelle** [comment]
@LevinMedia How does the search filter in the table header correspond to the product compare filter card? Should it be the same as searching in the "Show: Product comparison", but with inline tokens?

**Comment by LevinMedia** [comment]
@ryelle that's correct - Preview text would read "Search for products"

**Comment by ryelle** [comment]
Closing this "parent" issue to clean up; once inline tags are enabled in #496 we can add those to the table header search bar.
