### ISSUE TITLE
Analytics: Revenue Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#97]
Since this is the first report we are going to work on, this issue will act as a parent issue for all requisite child components:

**1366+ Viewports**

![1366+ Viewports](https://automattic.invisionapp.com/static-signed/live-embed/266158435/313168868/6/latest/RkIkat83FcDSkACqLpNyTKA4jIOXkjpu8kNlbbOfc2eifhDjdElEQSEopMUIrwOxJePIvOLeTAl3LYQ4wOH3SAlE/Revenue---Viewport-1366-2x.png)

**<738 Viewports**

![<783 Viewports](https://automattic.invisionapp.com/static-signed/live-embed/266158435/313951182/2/latest/nFrxHKGf2wpNzMw3cW7gQQ0CEWc4hyPPzfAssNnYBPi5JW4o2mkyT0JYLXMqnkO67ESdF9tOsCycFJlEEIX5s5AlE/Revenue---Viewport-Less-Than-783-2x.png)

**Background**
- [Report Requirements Spreadsheet](https://docs.google.com/spreadsheets/d/1CNb3oFeCyJzZHxBW2WxoxjCvd05LZZP0ndc0U5bOGwU/edit#gid=1512641570)

**Child Tasks**

- [x] #98 Mock API Creation
- [x] #59 Date Picker
- [x] Visualization Tabs
- [ ] Visualization Header
- [x] Line Visualization
- [x] Bar Visualization 
- [x] #94 Table Header Component
- [x] #93 Pagination Component
- [x] #92 Tabular Data Component
- [x] #224 data-layer API
- [x] #225 Hook up to live API data

**Design Questions**
- On stores that operate in regions where no tax is collected, do we hide tax columns by default?

**Comment by LevinMedia** [comment]
Updated comp with HiFi components

**Comment by LevinMedia** [comment]
Updated with new summary number components

**Comment by warrendholmes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Revenue Report](https://trello.com/c/LIgQTnW9/7-revenue-report)
